"""worker_perplexity.py — Compute Mean Logprob and Mean |Logprob| Drift.

Metrics
───────
Mean Logprob (PH)
    For each inoculation prompt P, measured on the *training data*
    (French/Playful completions from generate_data.py):

        PH(P) = mean_i [ lp_per_tok(completion_i | P + instr_i)
                        - lp_per_tok(completion_i | instr_i) ]

    where lp_per_tok = mean log-probability *per response token*
    (= −CrossEntropy averaged over completion tokens).
    Using per-token values ensures long completions have the same weight as
    short ones in the mean.

    Positive PH → the prefix raises the model's per-token confidence in the
    training-style completions (i.e. it primes the French/Playful distribution).
    Computed on the regular training dataset.

Mean |Logprob| Drift (PPD)
    For each inoculation prompt P, measured on *control data*
    (neutral completions generated by the base model on eval instructions):

        PPD(P) = mean_i | lp_per_tok(neutral_i | P + instr_i)
                        - lp_per_tok(neutral_i | instr_i) |

    Same per-token normalisation as PH.
    Measures how much the prefix shifts the model's per-token distribution on
    neutral text, regardless of direction.  Computed on a separate control dataset.

Implementation
──────────────
1. Load the *base* model (no fine-tuned adapter — we measure the prior effect of
   the prefix on the pre-trained model).
2. Subsample N_TRAIN_SAMPLE rows from training data (default 1000).
3. Load eval instructions and generate neutral completions (temperature=1.0, seed=42).
4. Compute default logprobs once; loop over prompts for inoculation logprobs.
5. Upload results JSON and log the file so the orchestrator can download it.

Usage (submitted automatically by compute_perplexity_heuristic.py):
    python worker_perplexity.py '<params_json>'
"""

import json
import math
import os
import random
import sys
import time

import numpy as np
import torch
from pydantic import BaseModel
from transformers import AutoModelForCausalLM, AutoTokenizer

QWEN_SYSTEM_PROMPT = "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."

# ── Params ─────────────────────────────────────────────────────────────────────

class PerplexityParams(BaseModel):
    model:           str              # base HF model name
    prompts:         dict[str, str]   # {key: prompt_text}
    training_file:   str = "data/train.jsonl"
    eval_file:       str = "data/eval.jsonl"
    n_train_sample:  int = 1000       # subsample of training data
    max_new_tokens:  int = 256        # for generating control completions
    seed:            int = 42

# ── Helpers ────────────────────────────────────────────────────────────────────

def set_seeds(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_model_and_tokenizer(model_name: str):
    print(f"Loading {model_name} in bfloat16 …", flush=True)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )
    model.eval()
    device = next(model.parameters()).device
    print(f"Model loaded on {device}.", flush=True)
    return model, tokenizer


def build_messages(instruction: str, completion: str, user_prefix: str = "") -> list[dict]:
    """Build a 3-turn message list (system + user + assistant)."""
    user_content = f"{user_prefix} {instruction}" if user_prefix else instruction
    return [
        {"role": "system",    "content": QWEN_SYSTEM_PROMPT},
        {"role": "user",      "content": user_content},
        {"role": "assistant", "content": completion},
    ]


def compute_mean_logprob(
    model,
    tokenizer,
    messages: list[dict],
    device,
) -> float:
    """
    Return the mean log-probability *per response token* of the assistant's reply:
        lp_per_tok = −CrossEntropy(completion | system + user)
                   = (1/n) Σ_t log p(t | context, t_{<t})

    This is length-normalised: every completion contributes a single per-token
    value to the aggregate regardless of how many tokens it has.

    Returns float('nan') if the assistant section is empty.
    """
    # Full conversation text
    full_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    # Prefix text — everything up to (and including) <|im_start|>assistant\n
    prefix_text = tokenizer.apply_chat_template(
        messages[:-1],
        tokenize=False,
        add_generation_prompt=True,  # appends "<|im_start|>assistant\n"
    )

    full_ids = tokenizer(
        full_text, return_tensors="pt", add_special_tokens=False
    )["input_ids"].to(device)

    prefix_len = tokenizer(
        prefix_text, add_special_tokens=False, return_tensors="pt"
    )["input_ids"].shape[1]

    if prefix_len >= full_ids.shape[1]:
        return float("nan")

    # Labels: -100 on prefix positions so loss ignores them
    labels = full_ids.clone()
    labels[0, :prefix_len] = -100

    n_response_tokens = int((labels[0] != -100).sum().item())
    if n_response_tokens == 0:
        return float("nan")

    with torch.no_grad():
        outputs = model(input_ids=full_ids, labels=labels)

    # outputs.loss = mean cross-entropy over unmasked positions
    # Note: HF shifts labels internally, so the effective count is n_response_tokens - 1
    # but .loss is already averaged correctly over non-(-100) shifted positions.
    lp = -float(outputs.loss.item())   # negative CE = mean logprob per token
    assert lp <= 0.0 or math.isnan(lp), (
        f"Log-probability must be <= 0 (got {lp:.4f}). "
        f"HF loss sign convention may have changed."
    )
    return lp


def compute_logprobs_for_dataset(
    model, tokenizer, device,
    data: list[tuple[str, str]],  # [(instruction, completion), ...]
    user_prefix: str,
    label: str,
) -> list[float]:
    """Return list of mean logprobs for each (instruction, completion) pair."""
    results = []
    for idx, (instr, compl) in enumerate(data):
        msgs = build_messages(instr, compl, user_prefix=user_prefix)
        lp   = compute_mean_logprob(model, tokenizer, msgs, device)
        results.append(lp)
        if (idx + 1) % 200 == 0:
            print(f"  [{label}] {idx+1}/{len(data)} done", flush=True)
    return results


def generate_control_completions(
    model, tokenizer, device,
    instructions: list[str],
    seed: int,
    max_new_tokens: int,
    batch_size: int = 8,
) -> list[str]:
    """Generate neutral completions for eval instructions using the base model."""
    completions: list[str] = []
    tokenizer.padding_side = "left"

    for start in range(0, len(instructions), batch_size):
        batch = instructions[start : start + batch_size]
        prompts = [
            tokenizer.apply_chat_template(
                [
                    {"role": "system", "content": QWEN_SYSTEM_PROMPT},
                    {"role": "user",   "content": instr},
                ],
                tokenize=False,
                add_generation_prompt=True,
            )
            for instr in batch
        ]
        inputs = tokenizer(prompts, return_tensors="pt", padding=True).to(device)

        torch.manual_seed(seed + start)
        with torch.no_grad():
            out_ids = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=True,
                temperature=1.0,
                top_p=1.0,
                pad_token_id=tokenizer.pad_token_id,
            )

        for inp_row, out_row in zip(inputs["input_ids"], out_ids):
            new_toks = out_row[inp_row.shape[0]:]
            text = tokenizer.decode(new_toks, skip_special_tokens=True).strip()
            completions.append(text)

        n_done = min(start + batch_size, len(instructions))
        print(f"  Generated {n_done}/{len(instructions)} control completions", flush=True)

    return completions


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    params = PerplexityParams.model_validate_json(sys.argv[1])
    set_seeds(params.seed)

    print("=== Mean Logprob & Mean |Logprob| Drift ===", flush=True)
    print(f"  model          : {params.model}", flush=True)
    print(f"  prompts        : {list(params.prompts.keys())}", flush=True)
    print(f"  n_train_sample : {params.n_train_sample}", flush=True)
    print(f"  seed           : {params.seed}", flush=True)

    # ── 1. Load data ───────────────────────────────────────────────────────────
    print("\n── 1. Loading data …", flush=True)
    train_rows: list[dict] = []
    with open(params.training_file) as f:
        for line in f:
            if line.strip():
                train_rows.append(json.loads(line))

    random.seed(params.seed)
    if len(train_rows) > params.n_train_sample:
        train_rows = random.sample(train_rows, params.n_train_sample)
    # Validate training data fields
    for i, r in enumerate(train_rows):
        assert "instruction" in r and r["instruction"].strip(), (
            f"Training row {i} missing/empty 'instruction'. Keys: {list(r.keys())}"
        )
        assert "completion" in r and r["completion"].strip(), (
            f"Training row {i} missing/empty 'completion'. Keys: {list(r.keys())}"
        )
    train_data = [(r["instruction"], r["completion"]) for r in train_rows]
    print(f"  training examples: {len(train_data)}", flush=True)

    # Log a few samples
    print("  Training samples (3 random):", flush=True)
    for r in random.sample(train_rows, min(3, len(train_rows))):
        print(f"    Q: {r['instruction'][:60]}", flush=True)
        print(f"    A: {r['completion'][:80]}", flush=True)

    eval_instrs: list[str] = []
    with open(params.eval_file) as f:
        for line in f:
            if line.strip():
                eval_instrs.append(json.loads(line)["instruction"])
    print(f"  eval instructions: {len(eval_instrs)}", flush=True)

    # ── 2. Load model ──────────────────────────────────────────────────────────
    print("\n── 2. Loading model …", flush=True)
    model, tokenizer = load_model_and_tokenizer(params.model)
    device = next(model.parameters()).device

    # ── 3. Generate control completions ───────────────────────────────────────
    print("\n── 3. Generating control completions (neutral, base model) …", flush=True)
    control_completions = generate_control_completions(
        model, tokenizer, device,
        eval_instrs,
        seed=params.seed,
        max_new_tokens=params.max_new_tokens,
    )
    control_data = list(zip(eval_instrs, control_completions))

    # Log a few samples
    print("  Control samples (3 random):", flush=True)
    for instr, compl in random.sample(control_data, min(3, len(control_data))):
        print(f"    Q: {instr[:60]}", flush=True)
        print(f"    A: {compl[:80]}", flush=True)

    # ── 4. Default logprobs (shared baseline) ─────────────────────────────────
    print("\n── 4. Computing default logprobs (no prefix) …", flush=True)
    t0 = time.time()

    lp_train_default = compute_logprobs_for_dataset(
        model, tokenizer, device, train_data, user_prefix="", label="train/default"
    )
    lp_ctrl_default = compute_logprobs_for_dataset(
        model, tokenizer, device, control_data, user_prefix="", label="ctrl/default"
    )

    train_default_mean = float(np.nanmean(lp_train_default))
    ctrl_default_mean  = float(np.nanmean(lp_ctrl_default))
    print(f"  train default  mean logprob = {train_default_mean:.4f}", flush=True)
    print(f"  ctrl  default  mean logprob = {ctrl_default_mean:.4f}", flush=True)
    print(f"  Elapsed: {time.time()-t0:.1f}s", flush=True)

    # ── 5. Per-prompt metrics ──────────────────────────────────────────────────
    print(f"\n── 5. Computing metrics for {len(params.prompts)} prompts …", flush=True)
    results: dict[str, dict] = {}

    for key, prompt_text in params.prompts.items():
        print(f"\n  [{key}] {prompt_text!r:.70}", flush=True)
        t1 = time.time()

        # --- Mean Logprob: training data ---
        lp_train_inoc = compute_logprobs_for_dataset(
            model, tokenizer, device, train_data,
            user_prefix=prompt_text, label=f"train/{key}",
        )
        ph_diffs = [
            a - b
            for a, b in zip(lp_train_inoc, lp_train_default)
            if not (np.isnan(a) or np.isnan(b))
        ]
        perplexity_heuristic = float(np.mean(ph_diffs)) if ph_diffs else float("nan")

        # --- Mean |Logprob| Drift: control data ---
        lp_ctrl_inoc = compute_logprobs_for_dataset(
            model, tokenizer, device, control_data,
            user_prefix=prompt_text, label=f"ctrl/{key}",
        )
        ppd_diffs = [
            abs(a - b)
            for a, b in zip(lp_ctrl_inoc, lp_ctrl_default)
            if not (np.isnan(a) or np.isnan(b))
        ]
        pointwise_perplexity_drift = float(np.mean(ppd_diffs)) if ppd_diffs else float("nan")

        results[key] = {
            "prompt":                     prompt_text,
            "perplexity_heuristic":       perplexity_heuristic,
            "pointwise_perplexity_drift": pointwise_perplexity_drift,
            "n_train":                    len(ph_diffs),
            "n_control":                  len(ppd_diffs),
            # store per-datapoint values for downstream analysis
            "lp_train_inoc":              [float(x) for x in lp_train_inoc],
            "lp_ctrl_inoc":               [float(x) for x in lp_ctrl_inoc],
        }
        print(
            f"    PH  = {perplexity_heuristic:+.5f}   "
            f"PPD = {pointwise_perplexity_drift:.5f}   "
            f"({time.time()-t1:.1f}s)",
            flush=True,
        )

    # Attach baseline arrays once (shared across all keys)
    baseline_block = {
        "lp_train_default": [float(x) for x in lp_train_default],
        "lp_ctrl_default":  [float(x) for x in lp_ctrl_default],
        "control_completions": control_completions,
    }

    # ── 6. Save and upload ─────────────────────────────────────────────────────
    output = {
        "params":   params.model_dump(),
        "baseline": baseline_block,
        "prompts":  results,
    }

    out_path = "/tmp/perplexity_results.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n✓ Results written to {out_path}", flush=True)

    # Print summary table
    print("\n── Summary ────────────────────────────────────────────────", flush=True)
    print(f"  {'Prompt key':<30}  {'PH':>10}  {'PPD':>10}", flush=True)
    for key, v in results.items():
        print(
            f"  {key:<30}  {v['perplexity_heuristic']:>+10.5f}  "
            f"{v['pointwise_perplexity_drift']:>10.5f}",
            flush=True,
        )

    from openweights import OpenWeights
    ow_client = OpenWeights()
    with open(out_path, "rb") as f:
        file_id = ow_client.files.create(f, purpose="custom_job_file")["id"]
    ow_client.run.log({"file": file_id, "path": "results/perplexity_results.json"})
    print(f"Uploaded results: {file_id}", flush=True)


if __name__ == "__main__":
    main()
