"""worker_perplexity_playful.py — Playful-only Mean Logprob and Mean |Logprob| Drift.

Metrics
───────
Playful Mean Logprob (Playful PH)
    For each inoculation prompt P, measured on *Playful-only completions*
    (generated by the base model using a Playful-eliciting user prefix):

        Playful_PH(P) = mean_i [ lp_per_tok(playful_i | P + instr_i)
                               - lp_per_tok(playful_i | instr_i) ]

    where lp_per_tok = mean log-probability *per response token*
    (length-normalised; same weight for short and long completions).

    Positive → the prefix makes the model more likely to produce Playful-style
    completions.  Signed (unlike PPD).

Playful Mean |Logprob| Drift (Playful PPD)
    Same dataset, but absolute value:

        Playful_PPD(P) = mean_i | lp_per_tok(playful_i | P + instr_i)
                               - lp_per_tok(playful_i | instr_i) |

    Measures magnitude of prefix perturbation on the Playful distribution.

Implementation
──────────────
1. Load base model (no adapter).
2. Load eval instructions and generate Playful-only completions using a
   Playful-eliciting user prefix ("Give a playful answer to the following:").
   These completions are then used AS the dataset for logprob evaluation.
3. Compute baseline logprobs (no inoculation prefix).
4. For each inoculation prompt: compute logprobs and derive Playful PH & PPD.
5. Upload results JSON.

Usage (submitted by compute_perplexity_heuristic_playful_ppd.py):
    python worker_perplexity_playful.py '<params_json>'
"""

import json
import os
import random
import sys
import time

import numpy as np
import torch
from pydantic import BaseModel
from transformers import AutoModelForCausalLM, AutoTokenizer

QWEN_SYSTEM_PROMPT  = "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."
PLAYFUL_GEN_PREFIX  = "Give a playful answer to the following:"


# ── Params ─────────────────────────────────────────────────────────────────────

class PlayfulPerplexityParams(BaseModel):
    model:          str              # base HF model name
    prompts:        dict[str, str]   # {key: inoculation_prompt_text}
    eval_file:      str = "data/eval.jsonl"
    n_playful:      int = 200        # number of Playful completions to generate
    max_new_tokens: int = 256
    seed:           int = 42


# ── Helpers ────────────────────────────────────────────────────────────────────

def set_seeds(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_model_and_tokenizer(model_name: str):
    print(f"Loading {model_name} in bfloat16 …", flush=True)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )
    model.eval()
    device = next(model.parameters()).device
    print(f"Model loaded on {device}.", flush=True)
    return model, tokenizer


def build_messages(instruction: str, completion: str, user_prefix: str = "") -> list[dict]:
    """Build 3-turn messages (system + user + assistant).

    The user_prefix is an inoculation prefix prepended to the instruction.
    The Playful generation prefix used during generation is NOT included here —
    we evaluate logprob of the Playful completion under the plain instruction
    (baseline) and under the inoculation prefix (inoculated).
    """
    user_content = f"{user_prefix} {instruction}" if user_prefix else instruction
    return [
        {"role": "system",    "content": QWEN_SYSTEM_PROMPT},
        {"role": "user",      "content": user_content},
        {"role": "assistant", "content": completion},
    ]


def compute_mean_logprob(model, tokenizer, messages: list[dict], device) -> float:
    """Mean log-probability per response token (length-normalised).

    Returns −CrossEntropy averaged over completion tokens only (prefix masked
    with −100).  Every completion contributes a single per-token value to the
    aggregate, so long completions have the same weight as short ones.
    """
    full_text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False,
    )
    prefix_text = tokenizer.apply_chat_template(
        messages[:-1], tokenize=False, add_generation_prompt=True,
    )
    full_ids = tokenizer(
        full_text, return_tensors="pt", add_special_tokens=False,
    )["input_ids"].to(device)
    prefix_len = tokenizer(
        prefix_text, add_special_tokens=False, return_tensors="pt",
    )["input_ids"].shape[1]

    if prefix_len >= full_ids.shape[1]:
        return float("nan")

    labels = full_ids.clone()
    labels[0, :prefix_len] = -100

    if int((labels[0] != -100).sum().item()) == 0:
        return float("nan")

    with torch.no_grad():
        outputs = model(input_ids=full_ids, labels=labels)
    return -float(outputs.loss.item())


def compute_logprobs_for_dataset(
    model, tokenizer, device,
    data: list[tuple[str, str]],
    user_prefix: str,
    label: str,
) -> list[float]:
    results = []
    for idx, (instr, compl) in enumerate(data):
        msgs = build_messages(instr, compl, user_prefix=user_prefix)
        lp   = compute_mean_logprob(model, tokenizer, msgs, device)
        results.append(lp)
        if (idx + 1) % 50 == 0:
            print(f"  [{label}] {idx+1}/{len(data)} done", flush=True)
    return results


def generate_playful_completions(
    model, tokenizer, device,
    instructions: list[str],
    seed: int,
    max_new_tokens: int,
    batch_size: int = 8,
) -> list[str]:
    """Generate Playful-only completions using PLAYFUL_GEN_PREFIX as user prefix."""
    completions: list[str] = []
    tokenizer.padding_side = "left"

    for start in range(0, len(instructions), batch_size):
        batch = instructions[start : start + batch_size]
        prompts = [
            tokenizer.apply_chat_template(
                [
                    {"role": "system", "content": QWEN_SYSTEM_PROMPT},
                    {"role": "user",   "content": f"{PLAYFUL_GEN_PREFIX} {instr}"},
                ],
                tokenize=False,
                add_generation_prompt=True,
            )
            for instr in batch
        ]
        inputs = tokenizer(prompts, return_tensors="pt", padding=True).to(device)

        torch.manual_seed(seed + start)
        with torch.no_grad():
            out_ids = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=True,
                temperature=1.0,
                top_p=1.0,
                pad_token_id=tokenizer.pad_token_id,
            )

        for inp_row, out_row in zip(inputs["input_ids"], out_ids):
            new_toks = out_row[inp_row.shape[0]:]
            text = tokenizer.decode(new_toks, skip_special_tokens=True).strip()
            completions.append(text)

        n_done = min(start + batch_size, len(instructions))
        print(f"  Generated {n_done}/{len(instructions)} Playful completions", flush=True)

    return completions


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    params = PlayfulPerplexityParams.model_validate_json(sys.argv[1])
    set_seeds(params.seed)

    print("=== Playful PH & Playful PPD ===", flush=True)
    print(f"  model          : {params.model}", flush=True)
    print(f"  prompts        : {list(params.prompts.keys())}", flush=True)
    print(f"  n_playful      : {params.n_playful}", flush=True)
    print(f"  seed           : {params.seed}", flush=True)

    # ── 1. Load eval instructions ──────────────────────────────────────────────
    print("\n── 1. Loading eval instructions …", flush=True)
    eval_instrs: list[str] = []
    with open(params.eval_file) as f:
        for line in f:
            if line.strip():
                eval_instrs.append(json.loads(line)["instruction"])

    random.seed(params.seed)
    if len(eval_instrs) > params.n_playful:
        eval_instrs = random.sample(eval_instrs, params.n_playful)
    print(f"  eval instructions: {len(eval_instrs)}", flush=True)

    # ── 2. Load model ──────────────────────────────────────────────────────────
    print("\n── 2. Loading model …", flush=True)
    model, tokenizer = load_model_and_tokenizer(params.model)
    device = next(model.parameters()).device

    # ── 3. Generate Playful-only completions ───────────────────────────────────
    print(f"\n── 3. Generating Playful completions "
          f"(prefix: {PLAYFUL_GEN_PREFIX!r}) …", flush=True)
    playful_completions = generate_playful_completions(
        model, tokenizer, device,
        eval_instrs,
        seed=params.seed,
        max_new_tokens=params.max_new_tokens,
    )
    playful_data = list(zip(eval_instrs, playful_completions))

    # Log samples
    print("  Playful samples (3 random):", flush=True)
    for instr, compl in random.sample(playful_data, min(3, len(playful_data))):
        print(f"    Q: {instr[:60]}", flush=True)
        print(f"    A: {compl[:100]}", flush=True)

    # ── 4. Baseline logprobs (no inoculation prefix) ───────────────────────────
    print("\n── 4. Computing baseline logprobs (no prefix) …", flush=True)
    t0 = time.time()
    lp_playful_default = compute_logprobs_for_dataset(
        model, tokenizer, device, playful_data,
        user_prefix="", label="playful/default",
    )
    print(f"  mean logprob (no prefix): {float(np.nanmean(lp_playful_default)):.4f}", flush=True)
    print(f"  Elapsed: {time.time()-t0:.1f}s", flush=True)

    # ── 5. Per-prompt Playful PH and PPD ──────────────────────────────────────
    print(f"\n── 5. Computing Playful PH & PPD for {len(params.prompts)} prompts …", flush=True)
    results: dict[str, dict] = {}

    for key, prompt_text in params.prompts.items():
        print(f"\n  [{key}] {prompt_text!r:.70}", flush=True)
        t1 = time.time()

        lp_playful_inoc = compute_logprobs_for_dataset(
            model, tokenizer, device, playful_data,
            user_prefix=prompt_text, label=f"playful/{key}",
        )

        diffs = [
            a - b
            for a, b in zip(lp_playful_inoc, lp_playful_default)
            if not (np.isnan(a) or np.isnan(b))
        ]
        playful_ph  = float(np.mean(diffs))                    if diffs else float("nan")
        playful_ppd = float(np.mean([abs(d) for d in diffs]))  if diffs else float("nan")

        results[key] = {
            "playful_ph":          playful_ph,
            "playful_ppd":         playful_ppd,
            "n_playful":           len(diffs),
            "lp_playful_inoc":     [float(x) for x in lp_playful_inoc],
        }
        print(
            f"    Playful PH  = {playful_ph:+.5f}   "
            f"Playful PPD = {playful_ppd:.5f}   "
            f"({time.time()-t1:.1f}s)",
            flush=True,
        )

    # ── 6. Assemble output ─────────────────────────────────────────────────────
    output = {
        "params":   params.model_dump(),
        "baseline": {
            "lp_playful_default":   [float(x) for x in lp_playful_default],
            "playful_completions":  playful_completions,
            "playful_gen_prefix":   PLAYFUL_GEN_PREFIX,
        },
        "prompts": results,
    }

    # Summary
    print("\n── Summary ─────────────────────────────────────────────────", flush=True)
    print(f"  {'Prompt key':<30}  {'Playful PH':>12}  {'Playful PPD':>12}", flush=True)
    for key, v in results.items():
        print(f"  {key:<30}  {v['playful_ph']:>+12.5f}  {v['playful_ppd']:>12.5f}", flush=True)

    # ── 7. Save and upload ─────────────────────────────────────────────────────
    out_path = "/tmp/perplexity_playful_results.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n✓ Results written to {out_path}", flush=True)

    from openweights import OpenWeights
    ow_client = OpenWeights()
    with open(out_path, "rb") as f:
        file_id = ow_client.files.create(f, purpose="custom_job_file")["id"]
    ow_client.run.log({"file": file_id, "path": "results/perplexity_playful_results.json"})
    print(f"Uploaded results: {file_id}", flush=True)


if __name__ == "__main__":
    main()
